---
#### Stop the Scalr services then pull down the new Scalr package ####
- name: Stop Service and Pull Package
  hosts: scalr-all
  user: ubuntu
  sudo: true
  gather_facts: false
  tasks:
   - debug:
      msg: Stopping All Scalr Services
   - include: scalr-server-stop.yml
   - debug:
      msg: Updating Scalr Packages
   - include: scalr-apt-update.yml
   
#### Reconfigure the Scalr servers ####
## Reconfigure the DB first so it is up for the worker or app to connect to during the upgrade process ##
## General rule for a multi-node architecture: Upgrade the DB first, worker second, the rest of the nodes after ##
- name: DB Reconfigure
  hosts: db
  user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: False
  tasks:
   - debug:
      msg: Reconfiguring Scalr Database Server
   - include: scalr-reconfig.yml
#- name: Worker Reconfigure
#  hosts: worker
#  user: ubuntu
#  sudo: true
#  gather_facts: False
#  tasks:
#   - debug:
#      msg: Reconfiguring Scalr App Server
#   - include: scalr-reconfig.yml
- name: App Reconfigure
  hosts: app
  user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: False
  tasks:
   - debug:
      msg: Reconfiguring Scalr Worker Server
   - include: scalr-reconfig.yml
